-- ███████████████████████████████████████████████████████████
-- DIABETES COMPANION V1 — CANONICAL DATABASE SCHEMA
-- Table: glucose_readings (LOCKED NAME)
-- ███████████████████████████████████████████████████████████

-- Create the glucose_readings table
CREATE TABLE IF NOT EXISTS glucose_readings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  glucose_mgdl INTEGER NOT NULL,
  measured_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  notes TEXT,
  meal_tag TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index on measured_at for faster sorting
CREATE INDEX IF NOT EXISTS idx_glucose_measured_at ON glucose_readings(measured_at DESC);

-- Index on created_at for recent logs
CREATE INDEX IF NOT EXISTS idx_glucose_created_at ON glucose_readings(created_at DESC);

-- Optional: Add Row Level Security (RLS) policies later when auth is added
-- ALTER TABLE glucose_readings ENABLE ROW LEVEL SECURITY;
